[tools]
python = "3.13"
uv = "latest"
typst = "latest"

[tasks.html]
description = "Generate the web site"
run = "uv run pelican content -o output -s pelicanconf.py"

[tasks.clean]
description = "Remove the generated files"
run = "[ ! -d output ] || rm -rf output"

[tasks.regenerate]
description = "Regenerate files upon modification"
run = "uv run pelican -r content -o output -s pelicanconf.py"

[tasks.serve]
description = "Serve site at http://localhost:8000"
run = "uv run pelican -l content -o output -s pelicanconf.py"

[tasks.devserver]
description = "Serve and regenerate together"
run = "uv run pelican -lr content -o output -s pelicanconf.py"

[tasks.publish]
description = "Generate using production settings"
run = "mise run resume:all && uv run pelican content -o output -s publishconf.py"

[tasks."resume:html"]
description = "Generate HTML resume"
run = "cd resume && uv run python yaml2html.py -f resume.yaml -o resume.md && mv resume.md ../content/pages/"

[tasks."resume:json"]
description = "Generate JSON resume"
run = "cd resume && uv run python yaml2json.py -f resume.yaml -o resume.json && mkdir -p ../content/downloads && mv resume.json ../content/downloads/"

[tasks."resume:pdf"]
description = "Generate PDF resume"
run = "cd resume && typst compile resume.typ && mkdir -p ../content/downloads && mv resume.pdf ../content/downloads/"

[tasks."resume:all"]
description = "Generate all resume formats"
run = "mise run resume:html && mise run resume:json && mise run resume:pdf"